### ISSUE TITLE
UnboundLocalError: local variable 'status' referenced before assignment

### ISSUE THREAD

**Issue by giuffridait** [George-iam/Midjourney_api#26]
When sending a new prompt, I see this error on the original terminal :
`=========================================
Traceback (most recent call last):
  File "/receiver.py", line 130, in <module>
    receiver.main()
  File "/receiver.py", line 107, in main
    self.collecting_results()
  File "/receiver.py", line 68, in collecting_results
    self.awaiting_list.loc[id] = [prompt, status]
UnboundLocalError: local variable 'status' referenced before assignment `

Is there any way I can fix it?

**Comment by zueliye** [comment]
Because you modified the model used by midjourney, continue to modify it to --v 5
